<?php
return array(
        'Base'=>
        array(
                'Main'=>
                array(
                        'levels'=>
                        array(
                                'maximum'=>'30',
                                'minimum'=>'1',
                        ),
                        'costs'=>
                        array(
                                'Wood'=>
                                array(
                                        'value'=>'90',
                                        'factor'=>'1.26',
                                ),
                                'Stone'=>
                                array(
                                        'value'=>'80',
                                        'factor'=>'1.275',
                                ),
                                'Iron'=>
                                array(
                                        'value'=>'70',
                                        'factor'=>'1.26',
                                ),
                        ),
                        'consumptions'=>
                        array(
                                'Population'=>
                                array(
                                        'value'=>'5',
                                        'factor'=>'1.17',
                                ),
                        ),
                        'build'=>
                        array(
                                'time'=>'900',
                                'factor'=>'1.2',
                        ),
                        'requirements'=>
                        array(
                        ),
                ),
                'Church'=>
                array(
                        'levels'=>
                        array(
                                'maximum'=>'3',
                                'minimum'=>'0',
                        ),
                        'costs'=>
                        array(
                                'Wood'=>
                                array(
                                        'value'=>'16000',
                                        'factor'=>'1.26',
                                ),
                                'Stone'=>
                                array(
                                        'value'=>'20000',
                                        'factor'=>'1.28',
                                ),
                                'Iron'=>
                                array(
                                        'value'=>'5000',
                                        'factor'=>'1.26',
                                ),
                        ),
                        'consumptions'=>
                        array(
                                'Population'=>
                                array(
                                        'value'=>'5000',
                                        'factor'=>'1.55',
                                ),
                        ),
                        'build'=>
                        array(
                                'time'=>'184980',
                                'factor'=>'1.2',
                        ),
                        'requirements'=>
                        array(
                                'Main'=>5,
                                'Farm'=>5,
                        ),
                ),
                'Church_f'=>
                array(
                        'levels'=>
                        array(
                                'maximum'=>'1',
                                'minimum'=>'0',
                        ),
                        'costs'=>
                        array(
                                'Wood'=>
                                array(
                                        'value'=>'160',
                                        'factor'=>'1.26',
                                ),
                                'Stone'=>
                                array(
                                        'value'=>'200',
                                        'factor'=>'1.28',
                                ),
                                'Iron'=>
                                array(
                                        'value'=>'50',
                                        'factor'=>'1.26',
                                ),
                        ),
                        'consumptions'=>
                        array(
                                'Population'=>
                                array(
                                        'value'=>'5',
                                        'factor'=>'1.55',
                                ),
                        ),
                        'build'=>
                        array(
                                'time'=>'8160',
                                'factor'=>'1.2',
                        ),
                        'requirements'=>
                        array(
                        ),
                ),
                'Place'=>
                array(
                        'levels'=>
                        array(
                                'maximum'=>'1',
                                'minimum'=>'0',
                        ),
                        'costs'=>
                        array(
                                'Wood'=>
                                array(
                                        'value'=>'10',
                                        'factor'=>'1.26',
                                ),
                                'Stone'=>
                                array(
                                        'value'=>'40',
                                        'factor'=>'1.275',
                                ),
                                'Iron'=>
                                array(
                                        'value'=>'30',
                                        'factor'=>'1.26',
                                ),
                        ),
                        'consumptions'=>
                        array(
                                'Population'=>
                                array(
                                        'value'=>'0',
                                        'factor'=>'1.17',
                                ),
                        ),
                        'build'=>
                        array(
                                'time'=>'10860',
                                'factor'=>'1.2',
                        ),
                        'requirements'=>
                        array(
                        ),
                ),
                'Statue'=>
                array(
                        'levels'=>
                        array(
                                'maximum'=>'1',
                                'minimum'=>'0',
                        ),
                        'costs'=>
                        array(
                                'Wood'=>
                                array(
                                        'value'=>'220',
                                        'factor'=>'1.26',
                                ),
                                'Stone'=>
                                array(
                                        'value'=>'220',
                                        'factor'=>'1.275',
                                ),
                                'Iron'=>
                                array(
                                        'value'=>'220',
                                        'factor'=>'1.26',
                                ),
                        ),
                        'consumptions'=>
                        array(
                                'Population'=>
                                array(
                                        'value'=>'10',
                                        'factor'=>'1.17',
                                ),
                        ),
                        'build'=>
                        array(
                                'time'=>'1500',
                                'factor'=>'1.2',
                        ),
                        'requirements'=>
                        array(
                        ),
                ),
                'Hide'=>
                array(
                        'levels'=>
                        array(
                                'maximum'=>'10',
                                'minimum'=>'0',
                        ),
                        'costs'=>
                        array(
                                'Wood'=>
                                array(
                                        'value'=>'50',
                                        'factor'=>'1.25',
                                ),
                                'Stone'=>
                                array(
                                        'value'=>'60',
                                        'factor'=>'1.25',
                                ),
                                'Iron'=>
                                array(
                                        'value'=>'50',
                                        'factor'=>'1.25',
                                ),
                        ),
                        'consumptions'=>
                        array(
                                'Population'=>
                                array(
                                        'value'=>'2',
                                        'factor'=>'1.17',
                                ),
                        ),
                        'build'=>
                        array(
                                'time'=>'1800',
                                'factor'=>'1.2',
                        ),
                        'requirements'=>
                        array(
                        ),
                ),
                'Wall'=>
                array(
                        'levels'=>
                        array(
                                'maximum'=>'20',
                                'minimum'=>'0',
                        ),
                        'costs'=>
                        array(
                                'Wood'=>
                                array(
                                        'value'=>'50',
                                        'factor'=>'1.26',
                                ),
                                'Stone'=>
                                array(
                                        'value'=>'100',
                                        'factor'=>'1.275',
                                ),
                                'Iron'=>
                                array(
                                        'value'=>'20',
                                        'factor'=>'1.26',
                                ),
                        ),
                        'consumptions'=>
                        array(
                                'Population'=>
                                array(
                                        'value'=>'5',
                                        'factor'=>'1.17',
                                ),
                        ),
                        'build'=>
                        array(
                                'time'=>'3600',
                                'factor'=>'1.2',
                        ),
                        'requirements'=>
                        array(
                                'Barracks'=>1,
                        ),
                ),
        ),
        'Storage'=>
        array(
                'Storage'=>
                array(
                        'capacity'=>
                        array(
                                'value'=>1000,
                                'factor'=>1.229,
                        ),
                        'levels'=>
                        array(
                                'maximum'=>'30',
                                'minimum'=>'1',
                        ),
                        'costs'=>
                        array(
                                'Wood'=>
                                array(
                                        'value'=>'60',
                                        'factor'=>'1.265',
                                ),
                                'Stone'=>
                                array(
                                        'value'=>'50',
                                        'factor'=>'1.27',
                                ),
                                'Iron'=>
                                array(
                                        'value'=>'40',
                                        'factor'=>'1.245',
                                ),
                        ),
                        'consumptions'=>
                        array(
                                'Population'=>
                                array(
                                        'value'=>'0',
                                        'factor'=>'1.15',
                                ),
                        ),
                        'build'=>
                        array(
                                'time'=>'1020',
                                'factor'=>'1.2',
                        ),
                        'requirements'=>
                        array(
                        ),
                ),
        ),
        'Consumer'=>
        array(
                'Farm'=>
                array(
                        'capacity'=>
                        array(
                                'value'=>240,
                                'factor'=>1.17,
                        ),
                        'levels'=>
                        array(
                                'maximum'=>'30',
                                'minimum'=>'1',
                        ),
                        'costs'=>
                        array(
                                'Wood'=>
                                array(
                                        'value'=>'45',
                                        'factor'=>'1.3',
                                ),
                                'Stone'=>
                                array(
                                        'value'=>'40',
                                        'factor'=>'1.32',
                                ),
                                'Iron'=>
                                array(
                                        'value'=>'30',
                                        'factor'=>'1.29',
                                ),
                        ),
                        'consumptions'=>
                        array(
                                'Population'=>
                                array(
                                        'value'=>'0',
                                        'factor'=>'1',
                                ),
                        ),
                        'build'=>
                        array(
                                'time'=>'1200',
                                'factor'=>'1.2',
                        ),
                        'requirements'=>
                        array(
                        ),
                ),
        ),
        'Production\\Unit'=>
        array(
                'Barracks'=>
                array(
                        'levels'=>
                        array(
                                'maximum'=>'25',
                                'minimum'=>'0',
                        ),
                        'costs'=>
                        array(
                                'Wood'=>
                                array(
                                        'value'=>'200',
                                        'factor'=>'1.26',
                                ),
                                'Stone'=>
                                array(
                                        'value'=>'170',
                                        'factor'=>'1.28',
                                ),
                                'Iron'=>
                                array(
                                        'value'=>'90',
                                        'factor'=>'1.26',
                                ),
                        ),
                        'consumptions'=>
                        array(
                                'Population'=>
                                array(
                                        'value'=>'7',
                                        'factor'=>'1.17',
                                ),
                        ),
                        'build'=>
                        array(
                                'time'=>'1800',
                                'factor'=>'1.2',
                        ),
                        'requirements'=>
                        array(
                                'Main'=>3,
                        ),
                ),
                'Stable'=>
                array(
                        'levels'=>
                        array(
                                'maximum'=>'20',
                                'minimum'=>'0',
                        ),
                        'costs'=>
                        array(
                                'Wood'=>
                                array(
                                        'value'=>'270',
                                        'factor'=>'1.26',
                                ),
                                'Stone'=>
                                array(
                                        'value'=>'240',
                                        'factor'=>'1.28',
                                ),
                                'Iron'=>
                                array(
                                        'value'=>'260',
                                        'factor'=>'1.26',
                                ),
                        ),
                        'consumptions'=>
                        array(
                                'Population'=>
                                array(
                                        'value'=>'8',
                                        'factor'=>'1.17',
                                ),
                        ),
                        'build'=>
                        array(
                                'time'=>'6000',
                                'factor'=>'1.2',
                        ),
                        'requirements'=>
                        array(
                                'Main'=>10,
                                'Barracks'=>5,
                                'Smith'=>5,
                        ),
                ),
                'Garage'=>
                array(
                        'levels'=>
                        array(
                                'maximum'=>'15',
                                'minimum'=>'0',
                        ),
                        'costs'=>
                        array(
                                'Wood'=>
                                array(
                                        'value'=>'300',
                                        'factor'=>'1.26',
                                ),
                                'Stone'=>
                                array(
                                        'value'=>'240',
                                        'factor'=>'1.28',
                                ),
                                'Iron'=>
                                array(
                                        'value'=>'260',
                                        'factor'=>'1.26',
                                ),
                        ),
                        'consumptions'=>
                        array(
                                'Population'=>
                                array(
                                        'value'=>'8',
                                        'factor'=>'1.17',
                                ),
                        ),
                        'build'=>
                        array(
                                'time'=>'6000',
                                'factor'=>'1.2',
                        ),
                        'requirements'=>
                        array(
                                'Main'=>10,
                                'Smith'=>10,
                        ),
                ),
                'Snob'=>
                array(
                        'levels'=>
                        array(
                                'maximum'=>'1',
                                'minimum'=>'0',
                        ),
                        'costs'=>
                        array(
                                'Wood'=>
                                array(
                                        'value'=>'15000',
                                        'factor'=>'2',
                                ),
                                'Stone'=>
                                array(
                                        'value'=>'25000',
                                        'factor'=>'2',
                                ),
                                'Iron'=>
                                array(
                                        'value'=>'10000',
                                        'factor'=>'2',
                                ),
                        ),
                        'consumptions'=>
                        array(
                                'Population'=>
                                array(
                                        'value'=>'80',
                                        'factor'=>'1.17',
                                ),
                        ),
                        'build'=>
                        array(
                                'time'=>'586800',
                                'factor'=>'1.2',
                        ),
                        'requirements'=>
                        array(
                                'Main'=>20,
                                'Smith'=>20,
                                'Market'=>10,
                        ),
                ),
        ),
        'Research'=>
        array(
                'Smith'=>
                array(
                        'levels'=>
                        array(
                                'maximum'=>'20',
                                'minimum'=>'0',
                        ),
                        'costs'=>
                        array(
                                'Wood'=>
                                array(
                                        'value'=>'220',
                                        'factor'=>'1.26',
                                ),
                                'Stone'=>
                                array(
                                        'value'=>'180',
                                        'factor'=>'1.275',
                                ),
                                'Iron'=>
                                array(
                                        'value'=>'240',
                                        'factor'=>'1.26',
                                ),
                        ),
                        'consumptions'=>
                        array(
                                'Population'=>
                                array(
                                        'value'=>'20',
                                        'factor'=>'1.17',
                                ),
                        ),
                        'build'=>
                        array(
                                'time'=>'6000',
                                'factor'=>'1.2',
                        ),
                        'requirements'=>
                        array(
                                'Main'=>5,
                                'Barracks'=>1,
                        ),
                ),
        ),
        'Market'=>
        array(
                'Market'=>
                array(
                        'levels'=>
                        array(
                                'maximum'=>'25',
                                'minimum'=>'0',
                        ),
                        'costs'=>
                        array(
                                'Wood'=>
                                array(
                                        'value'=>'100',
                                        'factor'=>'1.26',
                                ),
                                'Stone'=>
                                array(
                                        'value'=>'100',
                                        'factor'=>'1.275',
                                ),
                                'Iron'=>
                                array(
                                        'value'=>'100',
                                        'factor'=>'1.26',
                                ),
                        ),
                        'consumptions'=>
                        array(
                                'Population'=>
                                array(
                                        'value'=>'20',
                                        'factor'=>'1.17',
                                ),
                        ),
                        'build'=>
                        array(
                                'time'=>'2700',
                                'factor'=>'1.2',
                        ),
                        'requirements'=>
                        array(
                                'Main'=>3,
                                'Storage'=>2,
                        ),
                ),
        ),
        'Production\\Resource'=>
        array(
                'Wood'=>
                array(
                        'levels'=>
                        array(
                                'maximum'=>'30',
                                'minimum'=>'0',
                        ),
                        'costs'=>
                        array(
                                'Wood'=>
                                array(
                                        'value'=>'50',
                                        'factor'=>'1.25',
                                ),
                                'Stone'=>
                                array(
                                        'value'=>'60',
                                        'factor'=>'1.275',
                                ),
                                'Iron'=>
                                array(
                                        'value'=>'40',
                                        'factor'=>'1.245',
                                ),
                        ),
                        'consumptions'=>
                        array(
                                'Population'=>
                                array(
                                        'value'=>'5',
                                        'factor'=>'1.155',
                                ),
                        ),
                        'build'=>
                        array(
                                'time'=>'900',
                                'factor'=>'1.2',
                        ),
                        'requirements'=>
                        array(
                        ),
                ),
                'Stone'=>
                array(
                        'levels'=>
                        array(
                                'maximum'=>'30',
                                'minimum'=>'0',
                        ),
                        'costs'=>
                        array(
                                'Wood'=>
                                array(
                                        'value'=>'65',
                                        'factor'=>'1.27',
                                ),
                                'Stone'=>
                                array(
                                        'value'=>'50',
                                        'factor'=>'1.265',
                                ),
                                'Iron'=>
                                array(
                                        'value'=>'40',
                                        'factor'=>'1.24',
                                ),
                        ),
                        'consumptions'=>
                        array(
                                'Population'=>
                                array(
                                        'value'=>'10',
                                        'factor'=>'1.14',
                                ),
                        ),
                        'build'=>
                        array(
                                'time'=>'900',
                                'factor'=>'1.2',
                        ),
                        'requirements'=>
                        array(
                        ),
                ),
                'Iron'=>
                array(
                        'levels'=>
                        array(
                                'maximum'=>'30',
                                'minimum'=>'0',
                        ),
                        'costs'=>
                        array(
                                'Wood'=>
                                array(
                                        'value'=>'75',
                                        'factor'=>'1.252',
                                ),
                                'Stone'=>
                                array(
                                        'value'=>'65',
                                        'factor'=>'1.275',
                                ),
                                'Iron'=>
                                array(
                                        'value'=>'70',
                                        'factor'=>'1.24',
                                ),
                        ),
                        'consumptions'=>
                        array(
                                'Population'=>
                                array(
                                        'value'=>'10',
                                        'factor'=>'1.17',
                                ),
                        ),
                        'build'=>
                        array(
                                'time'=>'1080',
                                'factor'=>'1.2',
                        ),
                        'requirements'=>
                        array(
                        ),
                ),
        ),
);